version: "3"
services:
    api:
        build: 
          context: ..
          dockerfile: simplebank/Dockerfile 
        ports:
            - "8888:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "User@!1234FC6549"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        ports:
          - "1433:1433"